[build]
  base = "dist"
  command = "npm run build"
  publish = "dist/angular-firebase-app"



[[redirects]]
  from = "https://teal-dieffenbachia-5ffc3b.netlify.app/"
  to = "https://teal-dieffenbachia-5ffc3b.netlify.app/"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

