[[headers]]
  for = "/*"
  [headers.values]
  cache-control = '''
  max-age=0,
  no-cache,
  no-store,
  must-revalidate'''

[context.staging]
  command = "npm run build && cp ./custom-headers/_stagingHeaders ./dist/_headers"

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 301
force = true
